/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TypographyProps } from "./components/app-typography/app-typography";
export namespace Components {
    interface AppTypography {
        "variant"?: TypographyProps;
    }
}
declare global {
    interface HTMLAppTypographyElement extends Components.AppTypography, HTMLStencilElement {
    }
    var HTMLAppTypographyElement: {
        prototype: HTMLAppTypographyElement;
        new (): HTMLAppTypographyElement;
    };
    interface HTMLElementTagNameMap {
        "app-typography": HTMLAppTypographyElement;
    }
}
declare namespace LocalJSX {
    interface AppTypography {
        "variant"?: TypographyProps;
    }
    interface IntrinsicElements {
        "app-typography": AppTypography;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-typography": LocalJSX.AppTypography & JSXBase.HTMLAttributes<HTMLAppTypographyElement>;
        }
    }
}
